# Generated by Django 5.0.7 on 2024-09-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Limo_Manager', '0002_rename_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='passenger_limit',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=4),
        ),
    ]
