# Generated by Django 5.0.7 on 2025-03-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_dropoff_location_booking_dropoff_street_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='flight_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='other_airline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='airline',
            field=models.CharField(choices=[('Delta', 'Delta Airlines'), ('United', 'United Airlines'), ('American', 'American Airlines'), ('Southwest', 'Southwest Airlines'), ('Spirit', 'Spirit Airlines'), ('Frontier', 'Frontier Airlines'), ('Other', 'Other (Specify)')], max_length=50),
        ),
    ]
