# Generated by Django 5.0.7 on 2025-03-13 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_flight_number_booking_other_airline_and_more'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='airline',
            field=models.CharField(choices=[('Delta', 'Delta Airlines'), ('United', 'United Airlines'), ('American', 'American Airlines'), ('Southwest', 'Southwest Airlines'), ('Spirit', 'Spirit Airlines'), ('Frontier', 'Frontier Airlines'), ('Frontier', 'Frontier Airlines'), ('N/A', 'N/A')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='drivers.driver'),
        ),
    ]
